version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  traefik:
    image: traefik:1.7
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik/traefik.toml}:/traefik.toml
#     - ${ACME_JSON:-./traefik/acme.json}:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - ${TRAEFIK_URL_CONFIG:-traefik.frontend.rule=Host:traefik.docker.localhost}
    logging: *default-logging

  grafana:
    image: grafana/grafana:6.3.5
    restart: unless-stopped
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASS:-secret}
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - web
      - default
    labels:
      - "traefik.backend=grafana"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:waarneming.dryrun.link}
    logging: *default-logging

  postgres:
    image: timescale/timescaledb-postgis:latest-pg11
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REPLICATION_USER=${REPLICATION_USER}
      - REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
    networks:
      - default # postgres datasource grafana
      - pgnet
    shm_size: 256M
    logging: *default-logging
 
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    expose:
      - "80"
    ports:
      - "5050:80"
    networks:
      - web
      - pgnet
    volumes:
      - ./pgadmin/home:/root/.pgadmin
      - ./pgadmin/saved_queries:/var/lib/pgadmin/storage/pgadmin
    labels:
      - "traefik.backend=naturalis-pgadmin"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=80"
      - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:pgadmin.docker.localhost}
    logging: *default-logging

  sqlpad:
    image: 'sqlpad/sqlpad:latest'
    restart: unless-stopped
    ports:
      - '3030:3000'
    environment:
      - SQLPAD_DEBUG=TRUE
    volumes:
      - sqlpad:/var/lib/sqlpad
    logging: *default-logging

networks:
  pgnet:
    external: true
  web:
    external: true

volumes:
  grafanadata:
  pgadmindata:
  pglog:
  pgdata:
  pgadmin:
  sqlpad:
